language: python
python:
  - "3.4"

services:
  - mongodb
  - redis-server

before_install:
  - sudo apt-get update
  - mongoimport -d bastogne -c movie --file data/movie.json
  - mongoimport -d bastogne -c genres --file data/genres.json

install:
  - pip install -r requirements.txt

script:
  - python command/local_image.py
  - python command/complate_search.py
  - sh test.sh
